import { Bookmark, Check, ChevronRight, LockKeyhole, Star } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { formatPrice, prompts } from '@/data/catalog';
import PromptCard from '@/components/PromptCard';

export default function PromptDetailPage() {
  const { slug } = useParams();
  const prompt = prompts.find((item) => item.slug === slug) ?? prompts[0];
  const related = prompts.filter((item) => item.slug !== prompt.slug).slice(0, 2);
  return <div className="page-shell py-8 sm:py-12"><nav className="flex items-center gap-1 text-xs text-ink-300"><Link to="/explore" className="hover:text-forge-600">Catalog</Link><ChevronRight className="h-3 w-3" /><Link to={`/explore?category=${prompt.category}`} className="hover:text-forge-600">{prompt.category}</Link><ChevronRight className="h-3 w-3" /><span className="truncate text-ink-500">{prompt.title}</span></nav>
    <div className="mt-8 grid gap-10 lg:grid-cols-[minmax(0,1fr)_335px] lg:gap-14"><article><div className="flex flex-wrap gap-2"><span className="catalog-label">{prompt.category}</span><span className="catalog-label">Made for {prompt.model}</span></div><h1 className="display mt-5 max-w-3xl text-5xl leading-[.94] sm:text-6xl">{prompt.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-ink-500">{prompt.description}</p><div className="mt-7 flex items-center gap-3 border-y border-paper-300 py-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-paper-200 text-xs font-bold">{prompt.creatorInitials}</span><div><p className="text-sm font-bold text-ink-800">{prompt.creator}</p><p className="text-xs text-ink-500">Creator · {prompt.sales} people using it</p></div><span className="ml-auto flex items-center gap-1 text-sm font-bold"><Star className="h-4 w-4 fill-forge-500 text-forge-500" />{prompt.rating} <span className="font-normal text-ink-300">({prompt.reviews})</span></span></div>
      <section className="mt-10"><p className="eyebrow">Inside the prompt</p><div className="mt-3 border border-ink-700 bg-ink-900 p-6 text-paper-50"><p className="text-[.66rem] font-bold uppercase tracking-[.15em] text-forge-300">Preview · first section</p><p className="mt-5 font-mono text-sm leading-7 text-paper-100">{prompt.excerpt}</p><div className="relative mt-5 overflow-hidden border-t border-ink-700 pt-5"><p className="select-none font-mono text-sm leading-7 text-ink-300 blur-[4px]">Ask questions only after you have named the actual audience, decision, and boundary. Return the outcome in a format that can be acted on immediately.</p><div className="absolute inset-0 grid place-items-center bg-gradient-to-b from-transparent via-ink-900/70 to-ink-900"><span className="flex items-center gap-2 border border-ink-500 bg-ink-800 px-3 py-2 text-xs font-bold"><LockKeyhole className="h-3.5 w-3.5 text-forge-300" /> The rest is on the shelf</span></div></div></div></section>
      <section className="mt-10 grid gap-7 border-t border-paper-300 pt-8 sm:grid-cols-2"><div><p className="eyebrow">What you get</p><ul className="mt-4 space-y-3 text-sm leading-6 text-ink-500">{['The complete prompt, ready to adapt', 'Clear usage notes and context', 'A practical input and output example'].map((item) => <li key={item} className="flex gap-2"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-moss-500" />{item}</li>)}</ul></div><div><p className="eyebrow">Built for</p><div className="mt-4 flex flex-wrap gap-2">{prompt.tags.map((tag) => <span key={tag} className="catalog-label">{tag}</span>)}</div></div></section></article>
      <aside><div className="sticky top-6 border border-ink-800 bg-paper-100 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-ink-500">One-time access</p><p className="display mt-5 text-5xl">{formatPrice(prompt.price)}</p><p className="mt-3 text-sm leading-6 text-ink-500">Keep this prompt in your shelf and use it whenever the work calls for it.</p><button className="button-primary mt-6 w-full">{prompt.price === 0 ? 'Add to shelf' : 'Unlock full prompt'} <ChevronRight className="h-4 w-4" /></button><button className="mt-3 flex w-full items-center justify-center gap-2 py-2 text-sm font-bold text-ink-500 transition hover:text-forge-600"><Bookmark className="h-4 w-4" /> Save for later</button><div className="mt-5 border-t border-paper-300 pt-4 text-xs leading-5 text-ink-500"><strong className="text-ink-700">Try before you buy:</strong> A protected demo is available when this prompt supports it.</div></div></aside>
    </div><section className="mt-16 border-t border-paper-300 pt-9"><div className="mb-6 flex items-end justify-between"><div><p className="eyebrow">Keep exploring</p><h2 className="display mt-2 text-4xl">Nearby on the shelf.</h2></div><Link to="/explore" className="button-text">All prompts</Link></div><div className="grid gap-px border border-paper-300 bg-paper-300 md:grid-cols-2">{related.map((item, index) => <PromptCard key={item.slug} prompt={item} index={index} />)}</div></section>
  </div>;
}
